"""chatbot3_1

Revision ID: 52ec45e843e2
Revises: b1a3bab963fb
Create Date: 2026-03-09 20:15:57.621114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ec45e843e2'
down_revision: Union[str, Sequence[str], None] = 'b1a3bab963fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
