"""chatbot3

Revision ID: b1a3bab963fb
Revises: 50a6393d23f0
Create Date: 2026-03-09 18:59:22.670406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a3bab963fb'
down_revision: Union[str, Sequence[str], None] = '50a6393d23f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Messages', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Messages', 'users', ['usuario_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Messages', type_='foreignkey')
    op.drop_column('Messages', 'usuario_id')
    # ### end Alembic commands ###
